/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#920028",
        "on-primary": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-container": "#40000c",
        "on-primary-fixed": "#ffffff",
        "secondary": "#be0037",
        "outline-variant": "#c6c6c6",
        "secondary-fixed": "#ffb3b6",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-error": "#ffffff",
        "background": "#f9f9f9",
        "on-secondary-fixed": "#40000c",
        "on-surface-variant": "#474747",
        "tertiary-fixed": "#be0037",
        "outline": "#777777",
        "inverse-primary": "#c6c6c6",
        "primary-fixed": "#5e5e5e",
        "inverse-surface": "#303030",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#ffdada",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed-variant": "#7c0021",
        "on-surface": "#1b1b1b",
        "on-background": "#1b1b1b",
        "primary": "#000000",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed-dim": "#ff8890",
        "surface-tint": "#5e5e5e",
        "primary-container": "#3b3b3b",
        "surface-dim": "#dadada",
        "error": "#ba1a1a",
        "tertiary-container": "#e21e49",
        "surface": "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "on-error-container": "#410002",
        "primary-fixed-dim": "#474747",
        "on-tertiary-fixed": "#ffffff",
        "tertiary": "#7c0021",
        "secondary-container": "#ffc6c8",
        "surface-container": "#eeeeee",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffdada",
      },
      fontFamily: {
        headline: ["Lexend", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Lexend", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
    },
  },
  plugins: [],
};
